version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  flask:
    build: .
    container_name: flask_container
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql  # Make sure this matches the MySQL container name
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: task_manager

volumes:
  mysql_data:
