name: Deploy to EC2 with Docker Compose

on:
  push:
    branches:
      - main  # Change to your deployment branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-task-manager:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-task-manager:latest

      - name: Set up SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -e  # Exit script if any command fails

            # Ensure directory exists
            mkdir -p /home/ubuntu/flask-task-manager
            cd /home/ubuntu/flask-task-manager

            # Pull the latest image from Docker Hub
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/flask-task-manager:latest

            # Stop and remove old containers (if running)
            sudo docker-compose down || true

            # Ensure docker-compose.yml is present
            if [ ! -f docker-compose.yml ]; then
                echo "Error: docker-compose.yml not found!"
                exit 1
            fi

            # Start new containers
            sudo docker-compose up -d --remove-orphans

            # Remove unused images to save space
            sudo docker system prune -af
          EOF
